Loc_Model:
  model_path: 'results/training_model/liteloc_spline_astig/checkpoint.pkl'
Multi_Process:
  image_path: "/home/feiyue/LiteLoc_spline/pos2dot55w_size8_astig.tif"
  save_path: '/home/feiyue/LiteLoc_spline/liteloc_pos2dot55w_size8_astig.csv'
  time_block_gb: 0.5
  batch_size: 150
  sub_fov_size: 32
  over_cut: 8
  multi_gpu: False
  end_frame_num: null
  num_producers: 1