Loc_Model:
  model_path: '/home/feiyue/LiteLoc_spline/training_model/liteloc_spline_astig_0826/checkpoint.pkl'
Multi_Process:
  image_path: '/home/feiyue/LiteLoc_spline/pos4w5_frame5w4_size32.tif'
  save_path: '/home/feiyue/LiteLoc_spline/liteloc_pos4w5_frame5w4_size32_test.csv'
  time_block_gb: 0.5
  batch_size: 150
  sub_fov_size: 32
  over_cut: 8
  multi_gpu: False
  end_frame_num: null
  num_producers: 1