Camera:
  camera: sCMOS
  em_gain: 1.0
  surv_p: 0.5
  qe: 0.95
  spurious_c: 0.002
  sig_read: 1.535
  e_per_adu: 0.7471
  baseline: 100.0
PSF_model:
  z_scale: 700
  simulate_method: vector
  spline_psf:
    calibration_file: ../../calibrate_mat/Astigmatism_Tetraspeck_beads_2um_50nm_256_1_MMStack_Pos0.ome_3dcal.mat
    psf_extent:
    - - -0.5
      - 63.5
    - - -0.5
      - 63.5
    - None
    device_simulation: cuda
  vector_psf:
    objstage0: -500
    zernikefit_file: ../../beads_file/Astigmatism_Tetraspeck_beads_2um_50nm_256_1_MMStack_Pos0_calib_results.mat
    pixelSizeX: 110
    pixelSizeY: 110
    psfSizeX: 27
    NA: 1.5
    refmed: 1.406
    refcov: 1.524
    refimm: 1.518
    wavelength: 680
    zernikefit_map: null
    psfrescale: 0.5
    Npupil: 64
    robust_training: false
Training:
  max_epoch: 50
  eval_iteration: 500
  batch_size: 16
  valid_frame_num: 100
  em_per_frame: 10
  train_size:
  - 64
  - 64
  photon_range:
  - 4000
  - 40000
  result_path: ../../results/liteloc_demo1_calibrate_python/
  infer_data: ../../datasets/NPC_U2OS_Astigmatism_PSF_640_40mw_20ms_256_2/NPC_U2OS_640_40mw_20ms_256_2_MMStack_Pos0.ome.tif
  bg: 211
  perlin_noise: true
  pn_factor: 0.2
  pn_res: 64
  factor: null
  offset: null
  model_init: null
