Camera:
  camera: sCMOS  # 'sCMOS' or 'EMCCD'
  em_gain: 1.0  # If 'sCOMS' is used, em_gain should be set as 1.0.
  surv_p: 0.5  # Probability of on-state emitters appear in the next frame follows a simple binomial distribution since only three consecutive images are used in each unit.
  qe: 0.95  # Quantum efficiency
  spurious_c: 0.002
  sig_read: 1.535  # Gaussian read out noise
  e_per_adu: 0.7471  # Analog-to-digital conversion factor
  baseline: 100.0  # Final offset added to the image
PSF_model:
  z_scale: 700
  simulate_method: spline # 'spline' or 'vector'
  spline_psf:
    calibration_file: ../../calibrate_mat/Astigmatism_Tetraspeck_beads_2um_50nm_256_1_MMStack_Pos0.ome_3dcal.mat  #Please give an relative path.
    psf_extent:
    - - -0.5
      - 63.5
    - - -0.5
      - 63.5
    - None
    device_simulation: cuda
  vector_psf:
    objstage0: -500  # Nominal focal plane with respect to the coverslip, it should be set carefully when there is a refractive index (RI) mismatch between `refmed` and `refimm`. If there is no RI mismatch, `objstage0` becomes meaningless.
    zemit0: null
    zernikefit_file: ../../calibrate_mat/Astigmatism_Crimson_645_beads_defoucs_0_50nm_1_MMStack_Pos0.ome_3dcal_test.mat  # Only if 'zernikefit_file' is null, parameter setting below works.
    pixelSizeX: 110
    pixelSizeY: 110
    psfSizeX: 51
    NA: 1.5
    refmed: 1.406
    refcov: 1.524
    refimm: 1.518
    wavelength: 680
    zernikefit_map: null
    psfrescale: 0.5
    Npupil: 64
    robust_training: False
Training:
  max_epoch: 50  # Every epoch includes 'eval_iteration' training times.
  eval_iteration: 500  # Evaluation will be done per 'eval_iteration' training times.
  batch_size: 16
  valid_frame_num: 100  # Number of images in evaluation dataset, these images have the same size as the training data.
  em_per_frame: 10 # Average number of emitters per frame
  train_size:  # Size of simulated training images, set it small when GPU memory is limited.
  - 64
  - 64
  photon_range:  # Minimum and maximum possible photon numbers that could be assigned to each single molecule during training.
  - 4000
  - 40000
  result_path: ../../results/liteloc_fig3a/  # Please give a relative path. Path to save trained model
  infer_data: ../../datasets/NPC_U2OS_Astigmatism_PSF_640_40mw_20ms_256_2/NPC_U2OS_640_40mw_20ms_256_2_MMStack_Pos0.ome.tif # Please give an absolute path. Path of experimental data
  bg: null  # Only if 'infer_data' is null, bg will be loaded by this variable.
  perlin_noise: True  # Whether add the perlin noise to the uniform background `backg` to simulate non-uniform background.
  pn_factor: 0.2  # Should be in the range of [0,1], which implies PV degree of the added Perlin nonuniform background, set it small when experimental background looks uniform.
  pn_res: 64  # Resolution(or frequency) of the Perlin noise.
  factor: null  # To be compatible with decode, but not used in liteloc network.
  offset: null  # To be compatible with decode, but not used in liteloc network.
  model_init: null # If training is interrupted by mistake, you can set this variable to continue the training.