Camera:
  camera: 'sCMOS'
  em_gain: 1.0
  surv_p: 0.5
  margin_empty: 0.1
  qe: 1
  spurious_c: 0.000
  sig_read: 0.0001
  e_per_adu: 1
  baseline: 0
PSF_model:
  z_scale: 700
  simulate_method: 'vector'
  spline_psf:
    calibration_file: './calibrate_mat/astig_z_stack_wo_noise_3dcal.mat'
    psf_extent:
    -
      - 0
      - 128
    - - 0
      - 128
    - None
    device_simulation: 'cuda'
  vector_psf:
    Npixels: 51
    pixel_size_xy:
      - 100
      - 100
    objstage0: -800
    psf_size: 51  # repeat
    NA: 1.49
    refmed: 1.518
    refcov: 1.518
    refimm: 1.518
    wavelength: 660
    zemit0: null  # zemit0 can be calculated from objstage0 and one of them need to be not None.
    zernike_aber: "/home/feiyue/FD_DeepLoc/PSF_aber_map/Astigmatism(need lambda).mat"
    otf_rescale_xy:
      - 0.5
      - 0.5
    Npupil: 64
Training:
  max_epoch: 50
  eval_iteration: 500
  batch_size: 16
  valid_frame_num: 100
  em_per_frame: 40
  train_size:
  - 128
  - 128
  photon_range:
  - 3000
  - 7000
  result_path: './training_model/LiteLoc_astig_new_program_vector_astig_crlb_test/'
  infer_data: '/home/feiyue/LiteLoc_local_torchsimu/random_points/Astigmatism/hsnr_ld/1.tif'
  bg: 50  # bg can be calculated from infer_data, but one of them need to not null.
  perlin_noise: False
  pn_factor: 0.2
  pn_res: 64